/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include "stm32f407xx.h"
#include <stdint.h>

#define APP_ADDRESS  		0x08004000UL
#define APP_CRC_ADDR       (APP_ADDRESS + 0x08U)
#define APP_SIZE_ADDR      (APP_ADDRESS + 0x0CU)
#define APP_CODE_ADDR      (APP_ADDRESS + 0x10U)

typedef void (*pFunc)(void);

static void Bootloader_LED_Init(void)
{
    // PD12 on STM32F4-Discovery (example); adapt for your board
    RCC->AHB1ENR |= (1U << 3); // Enable GPIOD clock

    //GPIOD peripheral settings
    GPIOD->MODER &= ~(0x3U << (12U * 2));
    GPIOD->MODER |=  (0x1U << (12U * 2)); // output
    GPIOD->OTYPER &= ~(1U << 12);
    GPIOD->OSPEEDR &= ~(0x3U << (12U * 2));
    GPIOD->PUPDR &= ~(0x3U << (12U * 2));
}

static void Bootloader_LED_Toggle(void)
{
    GPIOD->ODR ^= (1U << 12);
}

static void Delay(volatile uint32_t d)
{
    while (d--) __NOP();	//NOP --> means no operation , takes once cpu cycle
}

//Sets CRC to 0xFFFFFFFF internally
static void CRC_HW_Init(void)
{
    RCC->AHB1ENR |= RCC_AHB1ENR_CRCEN;   // Enable CRC clock
    CRC->CR = CRC_CR_RESET;             // Reset CRC calculation unit
}

uint32_t crc32_hw_calculate(uint32_t start_addr, uint32_t size_bytes)
{
    uint32_t crc;
    uint32_t *p_word = (uint32_t *)start_addr;

    // Reset CRC unit (sets initial value to 0xFFFFFFFF)
    CRC->CR = CRC_CR_RESET;

    // Number of full 32-bit words
    uint32_t word_count = size_bytes / 4U;

    // Feed full words
    for (uint32_t i = 0; i < word_count; i++)
    {
        CRC->DR = __REV(p_word[i]);
    }

    // Handle remaining bytes (1 to 3)
    uint32_t remaining = size_bytes % 4U;
    if (remaining)
    {
        uint32_t last_word = 0xFFFFFFFFU;  // Padding with 0xFF
        uint8_t *p_byte = (uint8_t *)(start_addr + (word_count * 4U));

        for (uint32_t i = 0; i < remaining; i++)
        {
            ((uint8_t *)&last_word)[i] = p_byte[i];
        }

        CRC->DR = __REV(last_word);
    }

    // Read final CRC and apply final XOR
    crc = CRC->DR ^ 0xFFFFFFFFU;

    return crc;
}

#ifdef USE_SW_CRC
uint32_t crc32_calculate(const uint8_t *data, uint32_t length)
{
    uint32_t crc = 0xFFFFFFFF;

    for (uint32_t i = 0; i < length; i++)
    {
        crc ^= data[i];

        for (uint32_t bit = 0; bit < 8; bit++)
        {
            if (crc & 1)
                crc = (crc >> 1) ^ 0xEDB88320;  // reversed polynomial
            else
                crc >>= 1;
        }
    }

    return ~crc;
}
#endif

int bootloader_verify_app_crc(void)
{
    uint32_t stored_crc = *(uint32_t *)APP_CRC_ADDR;
    uint32_t app_size   = *(uint32_t *)APP_SIZE_ADDR;

    // Basic sanity checks
    if (app_size == 0 || app_size > (128 * 1024))
        return 0;

	#ifdef USE_SW_CRC
    uint32_t calculated_crc = crc32_calculate((uint8_t *)APP_CODE_ADDR, app_size);
	#else
    uint32_t calculated_crc = crc32_hw_calculate(APP_CODE_ADDR, app_size);
	#endif

    if (calculated_crc == stored_crc)
        return 1;   // CRC OK
    else
        return 0;   // CRC FAIL
}

static int app_is_valid(void)
{
	// checking if the stack pointer and reset pointer is from the valid application
	uint32_t app_sp    = *(uint32_t*)(APP_ADDRESS + 0U);	//application stack pointer
    uint32_t app_reset = *(uint32_t*)(APP_ADDRESS + 4U);	//application reset handler

    // Basic sanity checks:


    if ((app_sp & 0xFF000000U) != 0x20000000U)					//  - app_sp should be in SRAM region (0x2000_0000 to 0x3FFF_FFFF typically)
    	return 0;      											// stack pointer is not valid

    if ((app_reset < 0x08000000U) || (app_reset > 0x080FFFFFU)) //  - app_reset should be in valid flash region (0x0800_0000 .. 0x080F_FFFF usually) i.e 0x08004000
    	return 0; 												// not a valid flash pointer

    // Check CRC
    if (!bootloader_verify_app_crc())
    	return 0;

    return 1;	// both stack and reset pointer is valid
}

static void jump_to_app(void)
{
    uint32_t app_sp    = *(uint32_t*)(APP_ADDRESS + 0U);
    uint32_t app_reset = *(uint32_t*)(APP_ADDRESS + 4U);
    pFunc    reset_fun = (pFunc)app_reset;

    // Disable IRQs
    __disable_irq();

    // If DCache/ICache are enabled, it is safe to disable/clean them before jumping.
    // CMSIS provides SCB functions, but be careful if your app expects caches enabled.
#if defined (__DCACHE_PRESENT) && (__DCACHE_PRESENT == 1U)
    SCB_DisableDCache();
#endif
#if defined (__ICACHE_PRESENT) && (__ICACHE_PRESENT == 1U)
    SCB_DisableICache();
#endif

    // Set vector table to application
    SCB->VTOR = APP_ADDRESS;

    // Set application main stack pointer
    __set_MSP(app_sp);

    // Jump to application's Reset Handler (this does not return)
    reset_fun();
}

int main(void)
{
    Bootloader_LED_Init();
    CRC_HW_Init();

    // Small blink to indicate bootloader running
    for (int i = 0; i < 6; ++i)
    {
    	Bootloader_LED_Toggle();
    	Delay(400000);
    }

    if (app_is_valid())
    {
        // Optionally indicate "jumping" with a pattern and small delay
        for (int i = 0; i < 2; ++i)
        {
        	Bootloader_LED_Toggle();
        	Delay(200000);
        }
        jump_to_app();
    }

    // If we reach here, no valid app found -> stay in bootloader (blink forever)
    while (1)
    {
        Bootloader_LED_Toggle();
        for (volatile uint32_t i=0;i<1000000;i++); // coarse delay
    }
}

